services:
  app:
    build: .
    container_name: rails-app
    volumes:
      - .:/home/environment
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ["bash"]
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis-master:6379
    depends_on:
      - redis

  redis:
    container_name: redis-master
    image: redis:latest
    ports:
      - "6379:6379"
