development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: sample_app_development
# production:
  # adapter: redis
  # url: redis://redis:6379/1
  # channel_prefix: sample_app_production