development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: sample_app_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: sample_app_test

# production:
  # adapter: redis
  # url: redis://redis:6379/1
  # channel_prefix: sample_app_production